services:
  mongodb:
    image: mongo:latest
    container_name: orders-mongodb
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_DATABASE=orders_tb
      - MONGO_INITDB_ROOT_USERNAME=lumahdev
      - MONGO_INITDB_ROOT_PASSWORD=Mongodb@321
    volumes:
      - ./init:/docker-entrypoint-initdb.d
      - db:/data/db
      - configdb:/data/configdb
      - mongot:/data/mongot

  rabbitmq:
    image: rabbitmq:3.13-management
    container_name: rabbitmq-emailms
    ports:
      - "5672:5672"
      - "15672:15672"

volumes:
  db:
  configdb:
  mongot:
  rabbitmq_data:
  rabbitmq_log: