services:
  mongodb:
    image: mongo:latest
    container_name: orders-mongodb
    ports:
      - "27019:27017"
    environment:
      - MONGO_INITDB_DATABASE=orders
      - MONGO_INITDB_ROOT_USERNAME=lumahdev
      - MONGO_INITDB_ROOT_PASSWORD=Mongodb@321
    volumes:
      - ./init:/docker-entrypoint-initdb.d
      - db:/data/db
      - configdb:/data/configdb
      - mongot:/data/mongot

volumes:
  db:
  configdb:
  mongot: